CREATE TABLE SERIE4_LOG_I (
    ID_LOG NUMBER PRIMARY KEY,
    VALOR NUMBER,
    FECHA_REGISTRO DATE
);

CREATE SEQUENCE SERIE4_LOG_I_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE PR_INSERTAR_SERIE4 (
    p_valor IN NUMBER
) AS
BEGIN
    INSERT INTO SERIE4_LOG_I (ID_LOG, VALOR, FECHA_REGISTRO)
    VALUES (SERIE4_LOG_I_SEQ.NEXTVAL, p_valor, SYSDATE);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE PR_CONSULTAR_SUMA_SERIE4 (
    p_suma OUT NUMBER
) AS
BEGIN
    SELECT SUM(VALOR) INTO p_suma FROM SERIE4_LOG_I;
END;
/

COMMIT;